### PR TITLE
Rename resourceDNSimpleRecord to resourceDNSimpleZoneRecord

### PR DESCRIPTION
**Pull request by ecomba**
This PR renames `resourceDNSimpleRecord` to `resourceDNSimpleZoneRecord` as well as some of the schema's fields to better reflect the nomenclature used in our API.

### CODE REVIEW

**Review by onlyhavecans — APPROVED** [review]
Looks good to me and all tests pass (test & testacc)

I have a question; since this is a majorly breaking change, how do we denote that in the provider that we have changed its API in a major way? This change will break the primary use of the provider as far as I can tell.

**Review by DXTimer — CHANGES_REQUESTED** [review]
As the resource schema changes, there would be a need to state migrations to be written https://www.terraform.io/docs/extend/resources/state-migration.html

**Comment by ecomba** [comment]
> Looks good to me and all tests pass (test & testacc)
> 
> I have a question; since this is a majorly breaking change, how do we denote that in the provider that we have changed its API in a major way? This change will break the primary use of the provider as far as I can tell.

This will all be part of the v0.9 release, which we will not release till we've completed the tasks pending for the milestone (it's also a conversation and planning away with @weppos )

**Comment by ecomba** [comment]
> As the resource schema changes, there would be a need to state migrations to be written https://www.terraform.io/docs/extend/resources/state-migration.html

Good catch! Thank you so much @DXTimer !

**Comment by ecomba** [comment]
> As the resource schema changes, there would be a need to state migrations to be written https://www.terraform.io/docs/extend/resources/state-migration.html

I have now implemented said migration and tests.

**Review by DXTimer — APPROVED** [review]

**Pull request merged**
